### ISSUE TITLE
Image dataset visdrone

### ISSUE THREAD

**Issue by melaniihariono** [GNAYUOHZ/centernet-visdrone#3]
Hello, I wanna ask you, did you resize all of the images to 1280*960 ??? because I look in to the dataset, they all have different size on the training set visdrone.

Thank you!

**Comment by GNAYUOHZ** [comment]
yes，same size when training

**Comment by melanih** [comment]
Can you give me the code/reference to resize the image so the bounding boxes will be resize too?  Thank you..

**Comment by melaniihariono** [comment]
Can you show me how much losses did you get when you train the model??

**Comment by melaniihariono** [comment]
Because when I am training at 75 epoch I still get 1.4 losses :(. Fyi I have training for 140 epoch.
